let allStrings = {
    "english": {
        "menunewgame"			: "NEW GAME",
        "menucontinue"			: "CONTINUE",
        "menurules"				: "RULES",
        "menuoptions"			: "OPTIONS",
        "menucredits"			: "CREDITS",
        "rulesline1"			: "       - collect for score, use as ammo",
        "rulesline2"			: "       - shoot or lose the entire score",
        "rulesline3"			: "       - gives 1 shield, shoot for 10 points",
        "rulesline4"			: "       - slows down, shoot for 10 points",
        "optionschangelang"		: "CHANGE LANGUAGE",
        "optionsdeletesave"		: "DELETE SAVED GAME",
        "optionsdeletescore"	: "DELETE HIGH SCORE",
        "optionssfxyes"			: "+SFX",
        "optionsmusicyes"		: "+MUSIC",
        "optionssfxno"			: "-SFX",
        "optionsmusicno"		: "-MUSIC",
        "creditsline1"			: "PROGRAMMING: Alaric von Teplitz",
        "creditsline2"			: "ART: Alexey Kim",
        "creditsline3"			: "MUSIC: Makai Symphony, dl-sounds.com",
        "gameover"				: "GAME OVER",
        "gameoverreason"		: "You lost more than 100 points at once",
        "gameoverscore"			: "Your score was:",
        "gameoverhighscore"		: "High score is:",
        "back"					: "BACK"
    },
    "russian": {
        "menunewgame"			: "НОВАЯ ИГРА",
        "menucontinue"			: "ПРОДОЛЖИТЬ",
        "menurules"				: "ПРАВИЛА",
        "menuoptions"			: "НАСТРОЙКИ",
        "menucredits"			: "АВТОРЫ",
        "rulesline1"			: "       - очки и боеприпасы",
        "rulesline2"			: "       - обнулит счет. стреляйте, чтобы сбить",
        "rulesline3"			: "       - даст 1 щит. 10 очков, если сбить",
        "rulesline4"			: "       - замедлит. 10 очков, если сбить",
        "optionschangelang"		: "СМЕНИТЬ ЯЗЫК",
        "optionsdeletesave"		: "СБРОСИТЬ ПРОГРЕСС",
        "optionsdeletescore"	: "СБРОСИТЬ РЕКОРД",
        "optionssfxyes"			: "+ЗВУК",
        "optionsmusicyes"		: "+МУЗЫКА",
        "optionssfxno"			: "-ЗВУК",
        "optionsmusicno"		: "-МУЗЫКА",
        "creditsline1"			: "ПРОГРАММИСТ: Alaric von Teplitz",
        "creditsline2"			: "ХУДОЖНИК: Алексей Ким",
        "creditsline3"			: "МУЗЫКА: Makai Symphony, dl-sounds.com",
        "gameover"				: "КОНЕЦ ИГРЫ",
        "gameoverreason"		: "Вы потеряли больше 100 очков за раз",
        "gameoverscore"			: "Ваш счет был:",
        "gameoverhighscore"		: "Рекорд:",
        "back"					: "НАЗАД"
    }
}